### ISSUE TITLE
compiling output solved

### ISSUE THREAD

**Issue by pitreek** [MonsieurV/node-clock-sync#1]
I am noob in programming but I'm learning for sorry for maybe stupid question but I am basing on this code to pass java classes at university and really want to pass.
Question is when we have in code: 

pw.flush();
						System.out.println("MASTER - Sync message sent: " + syncMessage);
					} else {
						System.out.println("MASTER - Invalid node message received: " + nodeMessage);
					}

and in output:

run:
BUILD SUCCESSFUL (total time: 2 seconds)

I don't understand why can't I see output from println. Can you explain me why and what should I do to make it write in output. Probably because ping is 0 at localhost but I'm not sure.

Thanks in advice,
pitreek

**Comment by MonsieurV** [comment]
Hi @pitreek 

It seems like your not properly running the program but only compiling it. That's why your IDE (I presume Eclipse) give you "BUILD SUCCESSFUL (total time: 2 seconds)" as output.

To test this code, you must run multiple programs in the same time, as it is an implementation of a distributed algorithm (by the way, not the simpler way to begin at programming).

You must first launch the master node. In a terminal, run `java MasterNode` (before having compiling it using `javac MasterNode.java`).

Then run one or more client nodes. For that, run `java ClientNode ` (compile it before : `javac ClientNode.java`).

Hope this helps
MV

**Comment by MonsieurV** [comment]
I've added a debug message when the `MasterNode` start, so you will see something appears when the `MasterNode` start even if there is no client connection.

See 3c5e0ef07b03744b77d7dcd5202eee9a9d85e0a3

**Comment by pitreek** [comment]
Thank you very much. I realised what I done wrong but didn't knew how to find this issue page. Sorry for problem :) great code ! keep it up and thx

**Comment by MonsieurV** [comment]
Glad that's help. :)

Bye
